version: '3'

services:

  db:
    image: mysql:5.7
    restart: always
    container_name: "mysql_5.7"
    environment:
      MYSQL_ROOT_PASSWORD: 475182659
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
