version: "3"
services:
  nginx:
    image: nginx:alpine
    entrypoint: /opt/entry.sh
    container_name: nginx
    ports:
      - 8095:2345
    volumes:
      - ./nginx/entry.sh:/opt/entry.sh
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/embyCache:/var/cache/nginx/emby
    environment:
      # emby地址
      - EMBY_ADDRESS=http://xxxxxxxxxx:6908
      # xiaoya地址
      - ALIST_API=http://xxxxxxxxxx:5678
    restart: always
