version: "3"
services:
  nacos:
    image: nacos/nacos-server:v2.1.0 
    container_name: mynacos
    environment:
      - MODE=standalone
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
