version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - '2181:2181'
    networks:
      - kafka-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    depends_on:
      - 'zookeeper'
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

