version: "3"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: single
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
